# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3effd2e34a0c326aa057f38556dcccf548cc20f2fd91bdf435fda99e73cc70d444cb892bad1b420d8181503be6e87417ec2bc18b7f67c532e7f183511d6e7f90

test:
  secret_key_base: dc093a99af6aea2a8d437ba73b444ef05a59541ae8cd6eaa655f119039a39400f626354e79c3c53de190278bfa5c1da45f112319f075f35abf4dfdc7ad410ad6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
